---
driver_plugin: vagrant

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: debian-8.2
  run_list:
  - recipe[apt]

- name: centos-7.0

- name: centos-6.4

- name: opensuse-13.2
  driver:
    box: gsaslis/opensuse-13.2
    box_url: https://atlas.hashicorp.com/gsaslis/boxes/opensuse-13.2

- name: opensuse-13.1
  driver:
    box: opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql]
  attributes: {}

- name: contrib
  run_list:
  - recipe[postgresql::contrib]
  attributes:
    postgresql:
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-client
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql]
  excludes: ["centos-6.4", "centos-7.0", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"

- name: yum-pgdg-client
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql]
  excludes: ["ubuntu-12.04", "ubuntu-14.04", "debian-8.2", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      client:
        packages: ["postgresql94"]

- name: ruby
  run_list:
  - recipe[postgresql::ruby]
  - recipe[minitest-handler]
  attributes: {}

- name: server
  run_list:
  - recipe[apt]
  - recipe[minitest-handler]
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  attributes:
    postgresql:
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-server
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  excludes: ["centos-6.4", "centos-7.0", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        ssl_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
        ssl_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"

- name: yum-pgdg-server
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  excludes: ["ubuntu-12.04", "ubuntu-14.04", "debian-7.4", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      server:
        packages: ["postgresql94-server"]
        service_name: "postgresql-9.4"
      client:
        packages: ["postgresql94", "postgresql94-devel"]
      setup_script: "postgresql94-setup"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"

- name: apt-pgdg-client-ruby
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql]
  - recipe[postgresql::ruby]
  excludes: ["centos-6.4", "centos-7.0", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"

- name: yum-pgdg-client-ruby
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql]
  - recipe[postgresql::ruby]
  excludes: ["ubuntu-12.04", "ubuntu-14.04", "debian-7.4", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      client:
        packages: ["postgresql94", "postgresql94-devel"]

- name: apt-pgdg-server-pg_stat_statements
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql::ruby]
  - recipe[postgresql::contrib]
  excludes: ["centos-6.4", "centos-7.0", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_apt: true
      version: "9.4"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        shared_preload_libraries: "pg_stat_statements"
        ssl_cert_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
        ssl_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
      contrib:
        extensions:
          - pg_stat_statements

- name: yum-pgdg-server-pg_stat_statements
  run_list:
  - recipe[minitest-handler]
  - recipe[postgresql::ruby]
  - recipe[postgresql::contrib]
  excludes: ["ubuntu-12.04", "ubuntu-14.04", "debian-7.4", "opensuse-13.1", "opensuse-13.2"]
  attributes:
    postgresql:
      enable_pgdg_yum: true
      version: "9.4"
      server:
        packages: ["postgresql94-server"]
        service_name: "postgresql-9.4"
      password:
        postgres: "iloverandompasswordsbutthiswilldo"
      config:
        shared_preload_libraries: "pg_stat_statements"
      contrib:
        extensions:
          - pg_stat_statements
